# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
      - 202???
  paths:
    exclude:
      - .github

pr:
  branches:
    include:
      - master
      - 202???
  paths:
    exclude:
      - .github

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
  - repository: sonic-mgmt
    type: github
    name: sonic-net/sonic-mgmt
    ref: master
    endpoint: sonic-net
  - repository: buildimage
    type: github
    name: sonic-net/sonic-buildimage
    endpoint: sonic-net
    ref: master

parameters:
- name: TIMEOUT_IN_MINUTES_PR_TEST
  type: number
  default: 480

- name: CHECKOUT_SONIC_MGMT
  type: boolean
  default: true

variables:
- template: .azure-pipelines/azure-pipelines-repd-build-variables.yml@buildimage
- template: .azure-pipelines/template-variables.yml@buildimage
- name: CACHE_MODE
  value: rcache
- name: ENABLE_FIPS
  value: y
- name: BUILD_BRANCH
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    value: $(System.PullRequest.TargetBranch)
  ${{ else }}:
    value: $(Build.SourceBranchName)

stages:
- stage: BuildVS
  pool: sonicso1ES-amd64
  jobs:
  - template: .azure-pipelines/azure-pipelines-build.yml
    parameters:
      buildOptions: 'USERNAME=admin SONIC_BUILD_JOBS=$(nproc) BUILD_MULTIASIC_KVM=y INCLUDE_DHCP_SERVER=y ${{ variables.VERSION_CONTROL_OPTIONS }}'
      jobGroups:
      - name: vs

- stage: Build
  pool: sonicso1ES-amd64
  dependsOn: []
  jobs:
  - template: .azure-pipelines/azure-pipelines-build.yml
    parameters:
      buildOptions: 'USERNAME=admin SONIC_BUILD_JOBS=$(nproc) ${{ variables.VERSION_CONTROL_OPTIONS }}'
      jobGroups:
      - name: broadcom
        variables:
          swi_image: yes
          docker_syncd_rpc_image: yes
          dbg_image: yes
          platform_rpc: brcm
          INCLUDE_RESTAPI: y
      - name: mellanox
        variables:
          dbg_image: yes
          docker_syncd_rpc_image: yes
          session_monitor: yes
          platform_rpc: mlnx
      - name: marvell-prestera-arm64
        pool: sonicso1ES-arm64
        variables:
           PLATFORM_NAME: marvell-prestera
           PLATFORM_ARCH: arm64
      - name: marvell-prestera-armhf
        pool: sonicso1ES-armhf
        timeoutInMinutes: 1200
        variables:
          PLATFORM_NAME: marvell-prestera
          PLATFORM_ARCH: armhf
          INCLUDE_RESTAPI: y
      - name: nvidia-bluefield
        pool: sonicso1ES-arm64
        variables:
          PLATFORM_ARCH: arm64

- stage: Test
  dependsOn: BuildVS
  condition: and(succeeded(), and(ne(stageDependencies.BuildVS.outputs['vs.SetVar.SKIP_VSTEST'], 'YES'), in(dependencies.BuildVS.result, 'Succeeded', 'SucceededWithIssues')))
  variables:
  - group: SONiC-Elastictest
  - name: inventory
    value: veos_vtb
  - name: testbed_file
    value: vtestbed.csv
  - name: PTF_MODIFIED
    value: $[ coalesce(stageDependencies.BuildVS.vs.outputs['PublishAndSetPtfTag.PTF_MODIFIED'], stageDependencies.BuildVS.vs.outputs['script.PTF_MODIFIED'], stageDependencies.BuildVS.vs.outputs['script1.PTF_MODIFIED'], 'False') ]

# For every test job:
# continueOnError: false means it's a required test job and will block merge if it fails
# continueOnError: true means it's an optional test job and will not block merge even though it fails(unless a required test job depends on its result)

  jobs:
  - job: debug_variables
    pool: sonic-ubuntu-1c
    displayName: "Debug PTF_MODIFIED Variable"
    steps:
    - script: |
        echo "PTF_MODIFIED variable value: $(PTF_MODIFIED)"
        echo "Debug: Checking if PTF_MODIFIED is being passed correctly from BuildVS stage"
        if [ "$(PTF_MODIFIED)" = "True" ]; then
          echo "SUCCESS: PTF_MODIFIED is True"
        elif [ "$(PTF_MODIFIED)" = "False" ]; then
          echo "INFO: PTF_MODIFIED is False"
        else
          echo "ERROR: PTF_MODIFIED has unexpected value: $(PTF_MODIFIED)"
        fi
      displayName: "Debug PTF_MODIFIED Variable"

  - job:
    pool: sonictest
    displayName: "vstest"
    condition: false # agent pool don't work. disable this job to unblock PRs.
    timeoutInMinutes: 60
    steps:
    - template: .azure-pipelines/cleanup.yml
    - checkout: self
      clean: true
      submodules: recursive
      displayName: 'Checkout code'

    - script: |
        sudo rm -rf ../target
        sudo rm -rf ../*.deb
      displayName: "Cleanup"

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: sonic-buildimage.vs
      displayName: "Download sonic-buildimage.vs artifact"

    - script: |
        sudo src/sonic-swss-common/.azure-pipelines/build_and_install_module.sh
      displayName: "Install kernel modules"

    - script: |
        sudo apt-get update
        sudo apt-get install -y make libtool m4 autoconf dh-exec debhelper cmake pkg-config \
                         libhiredis-dev libnl-3-dev libnl-genl-3-dev libnl-route-3-dev libnl-nf-3-dev swig \
                         libpython2.7-dev libboost-dev libboost-serialization-dev uuid-dev libzmq5 libzmq3-dev  python3-pip \
                         cmake libgtest-dev libgmock-dev libyang-dev nlohmann-json3-dev
        sudo pip3 install pytest
        cd src/sonic-swss-common
        ./autogen.sh
        dpkg-buildpackage -rfakeroot -us -uc -b -j$(nproc)
        sudo dpkg -i --force-confask,confnew ../libswsscommon_*.deb
        sudo dpkg -i ../python3-swsscommon_*.deb
      displayName: "Compile sonic swss common"

    - script: |
        sudo docker load -i ../target/docker-sonic-vs.gz
        docker tag docker-sonic-vs:latest docker-sonic-vs:$(Build.BuildNumber)
        username=$(id -un)

        trap "docker ps; docker images; ip netns list; \
              docker rmi docker-sonic-vs:$(Build.BuildNumber); \
              ip netns list | grep -E [-]srv[0-9]+ | awk '{print $1}' | xargs -I {} sudo ip netns delete {}; \
              sudo chown -R ${username}.${username} .; \
              sudo chown -R ${username}.${username} $(System.DefaultWorkingDirectory)" EXIT
        pushd platform/vs/tests
        sudo py.test -v --junitxml=tr.xml --imgname=docker-sonic-vs:$(Build.BuildNumber)
      displayName: "Run vs tests"

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/tr.xml'
        testRunTitle: vstest

  # KVM based PR test jobs
  - template: .azure-pipelines/pr_test_template.yml@sonic-mgmt
    parameters:
      CHECKOUT_SONIC_MGMT: ${{ parameters.CHECKOUT_SONIC_MGMT }}
      GLOBAL_PARAMS:
        PTF_MODIFIED: $(PTF_MODIFIED)
