#Queue Type
ISAI_PARAM_A000 : "0"
ISAI_PARAM_P0_0_LS : "2304 2304 2304 2304 2304 2304 2304 2304"
ISAI_PARAM_P0_1_LS : "1736 1616 1616 1592 1592 1592 1592 1592"
ISAI_PARAM_P0_1_ALS : "200 80 80 56 56 56 56 56"
ISAI_PARAM_P1_0_LS : "768 768 768 768 768 768 768 768"
ISAI_PARAM_P1_0_LL : "1536 1536 1536 1536 1536 1536 1536 1536"
ISAI_PARAM_P1_1_LS : "1352 1232 1232 1208 1208 1208 1208 1208"
ISAI_PARAM_P1_1_LL : "3138 3138 3138 3138 3138 3138 3138 3138"
ISAI_PARAM_P1_1_ALS : "200 80 80 56 56 56 56 56"
ISAI_PARAM_P1_1_ALL : "86 86 86 86 86 86 86 86"
IVM_SAI_DP_PARAM_B_3_LL_1 : "60 60 60 60 60 60 60 60"
ISAI_PARAM_0_LL_TM : "0"
ISAI_PARAM_0_LL_TV : "400"
ISAI_PARAM_0_LS_TM : "0"
ISAI_PARAM_0_LS_TV : "400"
