IFCS_INIT_FILE : "/usr/share/sonic/hwsku/config_teralynx_MVTX9180_256x200G_OSFP.yaml"
IFCS_SKU_FILE : "/usr/share/sonic/hwsku/teralynx.MVTX9180"
IFCS_INNO_CLI_PORT : "9999"
IFCS_TARGET : "device"
INNOVIUM_DIR : "/innovium"
PYTHONPATH : "$INNOVIUM_DIR:$INNOVIUM_DIR/cmds:$INNOVIUM_DIR/scripts:$INNOVIUM_DIR/test/:$INNOVIUM_DIR/test/utils:$INNOVIUM_DIR/utils:$INNOVIUM_DIR/pyctypes:$INNOVIUM_DIR/ifcs_cmds:$INNOVIUM_DIR/testutil"
IVM_SAI_DATAPATH_CONFIG_FILE: "/usr/share/sonic/hwsku/ivm.sai.datapath.config.yaml"
IVM_SAI_PARAM_A0008: "64"
IVM_SAI_PARAM_A0016: "1,1,0,0,1"
IVM_SAI_PARAM_A0003: "4"
IVM_SAI_PARAM_A0059: "TRUE"
IVM_SAI_PARAM_A0007: "9"
