# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Build and push sonic-mgmt image

schedules:
- cron: "0 8 * * *"
  branches:
    include:
    - master
  always: true

trigger: none
pr:
  branches:
    include:
    - master
  paths:
    include:
    - dockers/docker-sonic-mgmt

resources:
  repositories:
  - repository: sonic-mgmt
    type: github
    name: sonic-net/sonic-mgmt
    ref: master
    endpoint: sonic-net

parameters:
- name: registry_url
  type: string
  default: sonicdev-microsoft.azurecr.io
- name: registry_conn
  type: string
  default: sonicdev

stages:
- stage: Build
  jobs:
  - job: Build
    pool: sonicso1ES-amd64
    timeoutInMinutes: 360
    steps:
    - template: cleanup.yml
    - checkout: self
      clean: true
    - script: |
        set -x
        sudo setfacl -R -b $(Agent.BuildDirectory)
      displayName: 'setfacl'

    - bash: |
        set -xe
        git submodule update --init --recursive -- src/sonic-platform-daemons src/sonic-genl-packet src/sonic-sairedis src/ptf src/sonic-device-data src/sonic-dash-api

        make NOBUSTER=1 NOBULLSEYE=1 SONIC_BUILD_JOBS=$(nproc) DEFAULT_CONTAINER_REGISTRY=publicmirror.azurecr.io ENABLE_DOCKER_BASE_PULL=y configure PLATFORM=generic DOCKER_BUILDKIT=0
        make -f Makefile.work BLDENV=bookworm SONIC_BUILD_JOBS=$(nproc) DEFAULT_CONTAINER_REGISTRY=publicmirror.azurecr.io ENABLE_DOCKER_BASE_PULL=y target/docker-sonic-mgmt.gz
        cp -r target $(Build.ArtifactStagingDirectory)/target
      env:
        REGISTRY_SERVER: ${{ parameters.registry_url }}
      displayName: Build docker-sonic-mgmt.gz

    - publish:  $(Build.ArtifactStagingDirectory)
      artifact: 'docker-sonic-mgmt'
      displayName: "Archive docker image sonic-mgmt"

    - bash: |
        set -ex
        docker load -i $(Build.ArtifactStagingDirectory)/target/docker-sonic-mgmt.gz
        docker tag docker-sonic-mgmt:latest $REGISTRY_SERVER/docker-sonic-mgmt:lastbuild
        docker images
      env:
        REGISTRY_SERVER: ${{ parameters.registry_url }}
      displayName: 'Load and tag docker-sonic-mgmt as lastbuild'

    - task: Docker@2
      displayName: 'Push docker-sonic-mgmt:lastbuild to registry'
      condition: succeeded()
      inputs:
        containerRegistry: ${{ parameters.registry_conn }}
        repository: docker-sonic-mgmt
        command: push
        tags: lastbuild

- stage: Test
  dependsOn: Build
  condition: and(succeeded(), in(dependencies.Build.result, 'Succeeded'))
  variables:
  - group: SONiC-Elastictest
  - name: BUILD_BRANCH
    value: $(Build.SourceBranchName)
  jobs:
    - template: .azure-pipelines/pr_test_template.yml@sonic-mgmt
      parameters:
        CHECKOUT_SONIC_MGMT: true
        OVERRIDE_PARAMS:
          REPO_NAME: "sonic-mgmt"
          SETUP_CONTAINER_PARAMS: "-i ${{ parameters.registry_url }}/docker-sonic-mgmt:lastbuild"

- stage: Publish
  dependsOn: Test
  condition: and(succeeded(), in(dependencies.Test.result, 'Succeeded'))
  jobs:
  - job: PublishAsLatest
    pool: sonicso1ES-amd64
    timeoutInMinutes: 60
    steps:
    - download: current
      artifact: 'docker-sonic-mgmt'
      displayName: "Download docker-sonic-mgmt image"

    - bash: |
        set -ex
        docker load -i $(Pipeline.Workspace)/docker-sonic-mgmt/target/docker-sonic-mgmt.gz
        docker tag docker-sonic-mgmt:latest $REGISTRY_SERVER/docker-sonic-mgmt:latest
        docker images
      env:
        REGISTRY_SERVER: ${{ parameters.registry_url }}
      displayName: 'Load and tag docker-sonic-mgmt as latest'

    - task: Docker@2
      displayName: 'Push docker-sonic-mgmt:latest to registry'
      condition: succeeded()
      inputs:
        containerRegistry: ${{ parameters.registry_conn }}
        repository: docker-sonic-mgmt
        command: push
        tags: latest
